import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "./providers";
import NavigatorBar from "./components/NavigatorBar";
import WalletProvider from "./components/WalletProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <WalletProvider>
          <Providers>
            <NavigatorBar />
            {children}
          </Providers>
        </WalletProvider>
      </body>
    </html>
  );
}
